PAL_NAMES = {
    "Alpaca": "Melpaca",
    "AmaterasuWolf": "Kitsun",
    "AmaterasuWolf_Dark": "Kitsun Noct",
    "Anubis": "Anubis",
    "BadCatgirl": "Nyafia ",
    "Baphomet": "Incineram",
    "Baphomet_Dark": "Incineram Noct",
    "Bastet": "Mau",
    "Bastet_Ice": "Mau Cryst",
    "BeardedDragon": "en_text",
    "BerryGoat": "Caprity",
    "BerryGoat_Dark": "Caprity Noct",
    "BirdDragon": "Vanwyrm",
    "BirdDragon_Ice": "Vanwyrm Cryst",
    "BlackCentaur": "Necromus",
    "BlackFurDragon": "Dragostrophe",
    "BlackGriffon": "Shadowbeak",
    "BlackMetalDragon": "Astegon",
    "BlackPuppy": "Smokie",
    "BlueberryFairy": "Prunelia",
    "BlueDragon": "Azurobe",
    "BluePlatypus": "Fuack",
    "BlueThunderHorse": "Azurmane",
    "Boar": "Rushoar",
    "BrownRabbit": "en_text",
    "CandleGhost": "Sootseer",
    "CaptainPenguin": "Penking",
    "Carbunclo": "Lifmunk",
    "CatBat": "Tombat",
    "CatMage": "Katress",
    "CatMage_Fire": "Katress Ignis",
    "CatVampire": "Felbat",
    "ChickenPal": "Chikipi",
    "ColorfulBird": "Tocotoco",
    "CowPal": "Mozzarina",
    "CuteButterfly": "Cinnamoth",
    "CuteFox": "Vixy",
    "CuteMole": "Fuddler",
    "DarkAlien": "Xenovader",
    "DarkCrow": "Cawgnito",
    "DarkMechaDragon": "Xenolord ",
    "DarkMutant": "en_text",
    "DarkScorpion": "Menasting",
    "DarkScorpion_Ground": "Menasting Terra",
    "Deer": "Eikthyrdeer",
    "Deer_Ground": "Eikthyrdeer Terra",
    "DreamDemon": "Daedream",
    "DrillGame": "Digtoise",
    "Eagle": "Galeclaw",
    "ElecCat": "Sparkit",
    "ElecLion": "Boltmane",
    "ElecPanda": "Grizzbolt",
    "FairyDragon": "Elphidran",
    "FairyDragon_Water": "Elphidran Aqua",
    "FeatherOstrich": "Dazemu",
    "FengyunDeeper": "Fenglope",
    "FengyunDeeper_Electric": "Fenglope Lux",
    "FireKirin": "Pyrin",
    "FireKirin_Dark": "Pyrin Noct",
    "FlameBambi": "Rooby",
    "FlameBuffalo": "Arsox",
    "FlowerDinosaur": "Dinossom",
    "FlowerDinosaur_Electric": "Dinossom Lux",
    "FlowerDoll": "Petallia",
    "FlowerRabbit": "Flopie",
    "FlyingManta": "Celaray",
    "FoxMage": "Wixen",
    "FoxMage_Dark": "Wixen Noct",
    "Ganesha": "Teafant",
    "Garm": "Direhowl",
    "GhostBeast": "Maraith",
    "GhostRabbit": "Nitemary",
    "GoldenHorse": "Gildane",
    "Gorilla": "Gorirat",
    "Gorilla_Ground": "Gorirat Terra",
    "GrassDragon": "en_text",
    "GrassMammoth": "Mammorest",
    "GrassMammoth_Ice": "Mammorest Cryst",
    "GrassPanda": "Mossanda",
    "GrassPanda_Electric": "Mossanda Lux",
    "GrassRabbitMan": "Verdash",
    "GrimGirl": "Splatterina",
    "GuardianDog": "Yakumo",
    "HadesBird": "Helzephyr",
    "HadesBird_Electric": "Helzephyr Lux",
    "HawkBird": "Nitewing",
    "Hedgehog": "Jolthog",
    "Hedgehog_Ice": "Jolthog Cryst",
    "HerculesBeetle": "Warsect ",
    "HerculesBeetle_Ground": "Warsect Terra",
    "Horus": "Faleris",
    "Horus_Water": "Faleris Aqua",
    "IceDeer": "Reindrix",
    "IceFox": "Foxcicle",
    "IceHorse": "Frostallion",
    "IceHorse_Dark": "Frostallion Noct",
    "JetDragon": "Jetragon",
    "Kelpie": "Kelpsea",
    "Kelpie_Fire": "Kelpsea Ignis",
    "KendoFrog": "Croajiro",
    "KendoFrog_Dark": "-",
    "KingAlpaca": "Kingpaca",
    "KingAlpaca_Ice": "Kingpaca Cryst",
    "KingBahamut": "Blazamut",
    "KingBahamut_Dragon": "Blazamut Ryu",
    "Kirin": "Univolt",
    "Kitsunebi": "Foxparks",
    "Kitsunebi_Ice": "Foxparks Cryst",
    "LavaGirl": "Flambelle",
    "LazyCatfish": "Dumud",
    "LazyDragon": "Relaxaurus",
    "LazyDragon_Electric": "Relaxaurus Lux",
    "LeafPrincess": "Lullu",
    "LilyQueen": "Lyleen",
    "LilyQueen_Dark": "Lyleen Noct",
    "LittleBriarRose": "Bristla",
    "LizardMan": "Leezpunk",
    "LizardMan_Fire": "Leezpunk Ignis",
    "Manticore": "Blazehowl",
    "Manticore_Dark": "Blazehowl Noct",
    "MimicDog": "Mimog",
    "Monkey": "Tanzee",
    "MoonQueen": "Selyne",
    "MopBaby": "Swee",
    "MopKing": "Sweepa",
    "MushroomDragon": "Shroomer",
    "MushroomDragon_Dark": "Shroomer Noct",
    "Mutant": "Lunaris",
    "MysteryMask": "Omascul",
    "NaughtyCat": "Grintale",
    "NegativeKoala": "Depresso",
    "NegativeOctopus": "Killamari",
    "NightBlueHorse": "Starryon",
    "NightFox": "Nox",
    "NightLady": "Bellanoir",
    "NightLady_Dark": "Bellanoir Libero",
    "Penguin": "Pengullet",
    "PinkCat": "Cattiva",
    "PinkKangaroo": "en_text",
    "PinkLizard": "Lovander",
    "PinkRabbit": "Ribbuny",
    "PinkRabbit_Grass": "Ribbuny Botan",
    "PlantSlime": "Gumoss",
    "PurpleSpider": "Tarantriss",
    "QueenBee": "Elizabee",
    "RaijinDaughter": "Dazzi",
    "RaijinDaughter_Water": "Dazzi Noct",
    "RedArmorBird": "Ragnahawk",
    "RobinHood": "Robinquill",
    "RobinHood_Ground": "Robinquill Terra",
    "Ronin": "Bushi",
    "Ronin_Dark": "Bushi Noct",
    "SaintCentaur": "Paladius",
    "SakuraSaurus": "Broncherry",
    "SakuraSaurus_Water": "Broncherry Aqua",
    "ScorpionMan": "Prixter",
    "Serpent": "Surfent",
    "Serpent_Ground": "Surfent Terra",
    "SharkKid": "Gobfin",
    "SharkKid_Fire": "Gobfin Ignis",
    "SheepBall": "Lamball",
    "SifuDog": "Dogen",
    "SkyDragon": "Quivern",
    "SkyDragon_Grass": "Quivern Botan",
    "SmallArmadillo": "Kikit",
    "SnowTigerBeastman": "Bastigor",
    "SoldierBee": "Beegarde",
    "Suzaku": "Suzaku",
    "Suzaku_Water": "Suzaku Aqua",
    "SweetsSheep": "Woolipop",
    "TentacleTurtle": "en_text",
    "ThunderBird": "Beakon",
    "ThunderDog": "Rayhound",
    "ThunderDragonMan": "Orserk",
    "Umihebi": "Jormuntide",
    "Umihebi_Fire": "Jormuntide Ignis",
    "VioletFairy": "Vaelet",
    "VolcanicMonster": "Reptyro",
    "VolcanicMonster_Ice": "Reptyro Cryst",
    "VolcanoDragon": "en_text",
    "WaterLizard": "en_text",
    "WeaselDragon": "Chillet",
    "WeaselDragon_Fire": "Chillet Ignis",
    "Werewolf": "Loupmoon",
    "Werewolf_Ice": "Loupmoon Cryst",
    "WhiteAlienDragon": "Xenogard",
    "WhiteDeer": "Celesdir",
    "WhiteMoth": "Sibelyx",
    "WhiteShieldDragon": "Silvegis",
    "WhiteTiger": "Cryolinx",
    "WhiteTiger_Ground": "Cryolinx Terra",
    "Windchimes": "Hangyu",
    "Windchimes_Ice": "Hangyu Cryst",
    "WingGolem": "Knocklem",
    "WizardOwl": "Hoocrates",
    "WoolFox": "Cremis",
    "Yeti": "Wumpo",
    "Yeti_Grass": "Wumpo Botan",
    "GrassBoss": "Zoe & Grizzbolt",
    "ForestBoss": "Lily & Lyleen",
    "DessertBoss": "Marcus & Faleris",
    "VolcanoBoss": "Axel & Orserk",
    "SnowBoss": "Victor & Shadowbeak",
    "SakurajimaBoss": "Saya & Selyne",
    "VikingBoss": "Bjorn & Bastigor"
}